{
    "error_message": "MES ENVIRONMENT CRASHING - EXCEPTION FOLLOWS \n\tSource Message: <Message Sender: , Recipients: , Directive: agent_confirm_init, Content: None>\n\tError Type: <class 'AttributeError'>\n\tError: 'DAEnvironment' object has no attribute 'number_of_agents'\n\n\tTrace Output: \n\t  File \"/mtree/mTree/microeconomic_system/environment.py\", line 218, in receiveMessage\n    directive_handler(self, message)\n\n\t  File \"da_environment.py\", line 122, in agent_confirm_init\n\n",
    "source_message": "<Message Sender: , Recipients: , Directive: agent_confirm_init, Content: None>",
    "error_type": "<class 'AttributeError'>",
    "error": "'DAEnvironment' object has no attribute 'number_of_agents'",
    "filename": "/mtree/mTree/microeconomic_system/environment.py",
    "lineno": 218,
    "name": "receiveMessage",
    "line": "directive_handler(self, message)"
}